### PR TITLE
feat(projectmwrapper: init): set help menu with correct info

### PR DESCRIPTION
**Pull request by actionless**
it was rather annoying to dig into source for realizing why "L" key from F1 help menu not working anymore 🥲

### CODE REVIEW

**Comment by kblaschke** [comment]
Just saw you did a similar thing than my PR from today, though I got no message about a new PR being opened. Need to look into my notification subscriptions.

Regarding the issue: If the `L` key was bound to locking presets, it was removed a good time ago, as the old SDL frontend has no sign of that either, except from stating it in the help menu.

The built-in key handler in libprojectM will be removed before the upcoming release, and this outdated help text will also be gone then. See my PR #30, I've added most hotkeys and also fixed the hotkey for adding waveforms, now using the shift key as a modifier. I'll just close this PR then.

**Comment by actionless** [comment]
thanks!
speaking of hotkey fixes and  random waveforms - are you planning to add also keyboard shortcuts for those?

using mouse is not an option because the mouse cursor will be visible on captured performance

**Comment by kblaschke** [comment]
That would certainly be possible if a random coordinate is picked instead of the mouse position.

Could you just create a feature request in this repo? Then it'll not be forgotten, since I'm currently deep into getting the release of the library done. And as a plus, you'll be notified when work is done on it or someone else has a comment.

**Comment by actionless** [comment]
thanks, i'll create

for now i'll think i'll just create a window manager rule to hide mouse pointer when it's over projectmsdl's window class

**Pull request closed without merging**
