### PR TITLE
CLI options for hard cuts and transition duration

### PR DESCRIPTION
**Pull request by nzoschke**
- Add CLI options for
  - transitionDuration
  - hardCutsEnabled
  - hardCutDuration
  - hardCutSensitivity
- Remove dynamic window title with pattern name

### CODE REVIEW

**Comment by nzoschke** [comment]
Note this builds on https://github.com/projectM-visualizer/frontend-sdl2/pull/44

**Comment by nzoschke** [comment]
Removing the dynamic title helps with my OBS window capture workflow. A static `projectM` lets me re-use a window capture source in OBS. If the window title changes, I need to create a new capture source every time.

**Review by kblaschke — CHANGES_REQUESTED** [review]
After PRs #48 and #52 are merged, I'd recommend to rereate this branch on the current master, then only cherry-pick commit [253684c](https://github.com/projectM-visualizer/frontend-sdl2/pull/46/commits/253684c464bf9d542ef326343ca948b6d49d61b0) into it, so the PR only merges this specific change.

**Comment by kblaschke** [comment]
No activity for four months on this PR, closing it for now.

Please feel free to reopen when the requested changed are implemented.

**Pull request closed without merging**
